server:
  port: 7075

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/atom_es
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    doc-expansion: none
  api-docs:
    path: /swagger-ui.html